from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from bson import ObjectId

from app.core.security import get_current_user
from app.db.mongodb import analyses_col

router = APIRouter()


@router.get("/roadmap/{analysis_id}/pdf")
async def export_roadmap_pdf(
    analysis_id: str,
    current_user: dict = Depends(get_current_user),
):
    """Export roadmap as PDF using WeasyPrint."""
    try:
        oid = ObjectId(analysis_id)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid ID")

    doc = await analyses_col().find_one(
        {"_id": oid, "user_id": current_user["user_id"]}
    )
    if not doc:
        raise HTTPException(status_code=404, detail="Analysis not found")

    result = doc["result"]
    roadmap = result.get("learning_roadmap", [])
    job_title = result.get("job_title", "Role")
    score = result.get("resume_score", {}).get("score", 0)

    # Build HTML for PDF
    modules_html = "".join([
        f"""<div style="margin:16px 0;padding:16px;border-left:4px solid #2563eb;background:#f8faff">
          <h3 style="margin:0 0 4px;color:#1e3a5f">Module {m.get('priority', i+1)}: {m.get('title','')}</h3>
          <p style="color:#555;margin:4px 0">{m.get('description','')}</p>
          <p style="color:#888;font-size:13px">⏱ {m.get('duration','')} · {m.get('category','')}</p>
          <p style="color:#666;font-size:13px">💡 {m.get('reason','')}</p>
          <a href="{m.get('resource_url','#')}" style="color:#2563eb;font-size:13px">{m.get('resource_url','')}</a>
        </div>"""
        for i, m in enumerate(roadmap)
    ])

    html = f"""<!DOCTYPE html>
<html><head>
<meta charset="UTF-8">
<style>
  body {{ font-family: Arial, sans-serif; padding: 40px; color: #1a1a2e; }}
  h1 {{ color: #1e3a5f; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }}
  .score {{ font-size: 48px; font-weight: bold; color: #2563eb; }}
</style>
</head>
<body>
  <h1>Learning Roadmap: {job_title}</h1>
  <p>Resume Match Score: <span class="score">{score}/100</span></p>
  <p>Candidate: {result.get('candidate_name','')}</p>
  <hr>
  <h2>Your Personalized Learning Path</h2>
  {modules_html}
  <p style="color:#999;font-size:12px;margin-top:40px">Generated by AI Adaptive Onboarding Engine v3</p>
</body></html>"""

    try:
        import weasyprint
        pdf_bytes = weasyprint.HTML(string=html).write_pdf()
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=roadmap-{analysis_id[:8]}.pdf"},
        )
    except ImportError:
        # Return HTML if WeasyPrint not installed
        return Response(content=html, media_type="text/html")
